name: sixth_man_travia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.4

dependencies:
  flutter:
    sdk: flutter

 # ------------ UI & UTILITIES ------------
  get: ^4.7.2
  responsive_sizer: ^3.3.1
  flutter_easyloading: ^3.0.5
  firebase_core: ^3.2.0
  file_picker: ^8.3.2
  permission_handler:
  google_fonts: ^6.2.1
  remixicon:
  fancy_shimmer_image:
  dotted_border:
  speech_to_text:
  appinio_swiper:
  carousel_slider:

  # ------------ FIREBASE & BACKEND ------------
  firebase_auth: 5.6.0
  cloud_firestore: ^5.1.0
  icons_launcher:
  url_launcher:
  firebase_storage:
  google_sign_in: ^6.2.1
  # local_auth: 2.3.0
  # flutter_secure_storage: 9.2.4
  paginate_firestore:
  intl:
  flutter_dash:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # ------------ DEVELOPMENT TOOLS ------------
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.6
flutter:
  uses-material-design: true

  assets:
    - assets/images/
